namespace :localize_strings do
  desc "Extracts DB Strings and creates views for detection by gettext"
  task extract_to_views: :environment do
    dump_constituencies
    dump_bodies
    dump_groups
    dump_group_types
    dump_constituency_types
    dump_position_types
  end
end

private

def file_header
  %(
    <!-- This file has been automatically generated by `rake localize_strings:extract_to_views`.
         Its purpose is to extract strings from the database so they can be localized. -->
  )
end

def output_filename(file_type)
  path_prefix = Rails.env.test? ? "tmp/localization" : "app/views/localization"
  FileUtils.mkdir_p(Rails.root + path_prefix)
  "#{path_prefix}/#{file_type}.html.erb"
end

def dump_bodies # well that's an ominous method name.
  file_type = 'bodies'

  filename = output_filename(file_type)
  bodies = Body.all

  File.open(filename, 'w') do |file|
    file.write file_header

    bodies.each do |body|
      file.write "<%= _(\"#{body.name}\") %>\n"
    end
  end
  p "    #{file_type}: Extracted #{bodies.count} strings"
end

def dump_constituencies
  file_type = 'constituencies'

  filename = output_filename(file_type)
  constituencies = Constituency.all

  File.open(filename, 'w') do |file|
    file.write file_header

    constituencies.each do |constituency|
      file.write "<%= _(\"#{constituency.name}\") %>\n"
    end
  end
  p "    #{file_type}: Extracted #{constituencies.count} strings"
end

def dump_constituency_types
  file_type = 'constituency_types'

  filename = output_filename(file_type)
  constituency_types = ConstituencyType.all

  File.open(filename, 'w') do |file|
    file.write file_header

    constituency_types.each do |constituency_type|
      file.write "<%= _(\"#{constituency_type.name}\") %>\n"
      file.write "<%= _(\"#{constituency_type.description}\") %>\n"
    end
  end
  p "    #{file_type}: Extracted #{constituency_types.count} strings"
end

def dump_group_types
  file_type = 'group_types'

  filename = output_filename(file_type)
  group_types = GroupType.all

  File.open(filename, 'w') do |file|
    file.write file_header

    group_types.each do |group_type|
      file.write "<%= _(\"#{group_type.name}\") %>\n"
    end
  end
  p "    #{file_type}: Extracted #{group_types.count} strings"
end

def dump_groups
  file_type = 'groups'

  filename = output_filename(file_type)
  groups = Group.all

  File.open(filename, 'w') do |file|
    file.write file_header

    groups.each do |group|
      file.write "<%= _(\"#{group.name}\") %>\n"
    end
  end
  p "    #{file_type}: Extracted #{groups.count} strings"
end

def dump_position_types
  file_type = 'position_types'

  filename = output_filename(file_type)
  position_types = PositionType.all

  File.open(filename, 'w') do |file|
    file.write file_header

    position_types.each do |position_type|
      file.write "<%= _(\"#{position_type.title}\") %>\n"
      file.write "<%= _(\"#{position_type.short_description}\") %>\n"
    end
  end
  p "    #{file_type}: Extracted #{position_types.count} strings"
end
