default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  password: <%= Rails.application.secrets[:db][:password] %>
  pool: 5
  username: <%= Rails.application.secrets[:db][:username] %>

development:
  <<: *default

  database: whoismytd_develop
  socket: /tmp/mysql.sock

production:
  <<: *default

  database: whoismytd_production
  url: <%= ENV["DATABASE_URL"] %>
  socket: /tmp/mysql.sock

staging:
  <<: *default

  database: whoismytd_develop
  socket: /tmp/mysql.sock

test:
  <<: *default

  database: whoismytd_test
  socket: /tmp/mysql.sock
