# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  mapit_url: <%= ENV["MAPIT_URL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db:
    password: <%= ENV["DB_PASSWORD"] %>
    username: <%= ENV["DB_USERNAME"] %>
  google_analytics_key: <%= ENV["GOOGLE_ANALYTICS_KEY"] %>
  google_maps_client_key: <%= ENV["GOOGLE_MAPS_CLIENT_KEY"] %>
  mixpanel_key: <%= ENV["MIXPANEL_KEY"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>

test:
  mapit_url: <%= ENV["MAPIT_URL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db:
    password: <%= ENV["DB_PASSWORD"] %>
    username: <%= ENV["DB_USERNAME"] %>
  mixpanel_key: <%= ENV["MIXPANEL_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mapit_url: <%= ENV["MAPIT_URL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db:
    password: <%= ENV["DB_PASSWORD"] %>
    username: <%= ENV["DB_USERNAME"] %>
  google_analytics_key: <%= ENV["GOOGLE_ANALYTICS_KEY"] %>
  google_maps_client_key: <%= ENV["GOOGLE_MAPS_CLIENT_KEY"] %>
  new_relic_key: <%= ENV["NEW_RELIC_LICENSE_KEY"] %>
  logentries_key: <%= ENV["LOGENTRIES_KEY"] %>
  mixpanel_key: <%= ENV["MIXPANEL_KEY"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
